Show tx cumulative weight when mouse hover
iotaledger/iotavisualization pull request #23
Opened 2018-02-02 10:23 UTC by mlouielu

Using `approving.nodes` we can get the cumulative weight of the hovered transaction.

But this assume each transaction weight is 1, and it is unrelate to X axis time.

2018-02-04 14:35 UTC, alongalky requested changes
I like the way the hoveredNode grows, it's a really nice touch. However in my opinion the format C: 13 is not clear enough, I want it to be more self explanatory.

I thought of something like a tooltip with various stats (cumulative weight, time of transaction, number of direct approvers). I don't want everything in the same pull request of course, but at least the basic shape.

2018-02-04 14:35 UTC, alongalky commented on src/components/Tangle.js
> +              {props.hoveredNode === node ? 'C:' + props.hoveredNodeWeight : node.name}
This should be added to the prop types validation (line 188)

2018-02-04 14:35 UTC, alongalky commented on src/components/Tangle.js
> +              nodeRadius={props.hoveredNode === node ? props.nodeRadius * 1.5 : props.nodeRadius}
Nice touch!

2018-02-05 06:02 UTC, mlouielu commented
Update with tooltip. When the mouse hover a transaction, it will show up cumulative weight and score.

This will still need to deal with mobile env in the future.

2018-02-05 18:01 UTC, alongalky commented
I love the tooltip! Just a few things:

1. packages.json needs to be updated with the new dependency (rc-tooltip), and the package lock file as well.
2. Tangle.propTypes needs to be updated (end of Tangle.js)
3. Single quotes in "top" in Tangle.js in 140 (sorry!)
4. I prefer to have just cumulative weight, as score isn't an important property and I prefer to take up less screen real estate.

Thanks a lot for your contribution!

2018-02-06 13:06 UTC, alongalky requested changes

2018-02-06 13:06 UTC, alongalky commented on src/components/Tangle.js
> +            visible={props.hoveredNode === node}
Add the property key={node.name}. This is required by React, or it throws a warning (you can see it in the browser debug console).

![image](https://user-images.githubusercontent.com/13794950/35820869-ad55a5ea-0aaf-11e8-9d2f-7f36dad36ac8.png)

2018-02-09 03:50 UTC, mlouielu commented
I would like to keep score item since it will give the user the perspective of choosing tips, it will be useful when doing one-by-one animation. Or fall back to show this prop when the transaction is a tips. How do you think?

2018-02-11 09:00 UTC, alongalky commented
I just don't see why it matters (for tips or otherwise). It's pretty arbitrary, and simply gets big as the tangle gets longer

2018-03-15 14:39 UTC, alongalky commented
Closing, merged manually

2018-03-15 14:39 UTC, closed without merging